### ISSUE TITLE
File .git/refs/gino_keva not created automatically

### ISSUE THREAD

**Issue by wafec** [philips-software/gino-keva#1]
I was trying to use gino-keva here using an Ubuntu instance in a simple Github project. When a ran the "gino-keva set test-key test_value" command then I got none message in the command line. Seemed that it worked. But when I tried to retrieve the value, it was not there. So I tried again but adding the --push option then it throws an error saying that the refs/gino-keva could not be found. Thus, I created the folder manually and then executed the command again and it worked.

Should we create this folder manually? Or might we get this automatically? I went guided by the errors that appeared in the command line and seem it worked and I can run all the commands that are in the examples provided. But without creating this folder I could do nothing.

**Comment by wyarde** [comment]
Hi @wafec,

Apologies for the initial bad experience. Manipulating the .git folder is (of course) not expected. Since this is a very new project, it is more than likely there is an actual issue in the code somewhere so I'm glad you raised this issue.

Could you help me with some more details:
- The oddity here is the folder `.git/refs/gino-keva` which you mention. Is this indeed the correct path? The default location where git would store the reference is in a file (not directory) at `.git/refs/notes/gino_keva` (with an underscore)
- Regardless of the above, could you provide the exact steps to replicate the error? Also please include the "--verbose" flag and capture the output.

Note that I expect it's probably not required to push the notes upstream to replicate the issue. That would make it a bit easier to debug and reset.

Let's figure this out!

**Comment by wafec** [comment]
Hi,

I hope this may help. I created a fresh project just to reproduce the same steps. Below the logs.

```console
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva set test-key test_value
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva set test-key test_value --verbose
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
DEBU[0001] Looking for git notes...                      hash=HEAD
DEBU[0002] Found note                                    note="{\"TEST_KEY\":{\"data\":\"test_value\",\"source\":\"10aca435\"}}\n"
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva get test-key test_value --verbose
FATA[0000] accepts 1 arg(s), received 2
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva get test-key --verbose
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
DEBU[0001] Looking for git notes...                      hash=HEAD
DEBU[0001] Found note                                    note="{\"TEST_KEY\":{\"data\":\"test_value\",\"source\":\"10aca435\"}}\n"
test_valuewallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva set key1 value1 --verbose --push
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
FATA[0001] Invalid key: last character is not a letter
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva set key1 value1_value --verbose --push
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
FATA[0001] Invalid key: last character is not a letter
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva set key1_key value1_value --verbose --push
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
DEBU[0001] Looking for git notes...                      hash=HEAD
DEBU[0001] Found note                                    note="{\"TEST_KEY\":{\"data\":\"test_value\",\"source\":\"10aca435\"}}\n"
DEBU[0001] Pushing notes...
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ gino-keva get key1_key
value1_valuewallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ ls .git
FETCH_HEAD  HEAD  config  description  hooks  index  info  logs  objects  packed-refs  refs
wallace@NLYBSTQVP5NB575:/mnt/c/Git/gino-keva-test$ ls .git/refs
heads  notes  remotes  tags
``` 

This time seems I could retrieve the data but the FATAL error is still happening. I did not know also that I can not create keys ending with a numeric symbol. Nice to test it.  Looking at the logs, the values and keys were found but I have no clue on how the program uses this file gino-keva. Is this tool intended to work even in the absence of such file?

**Comment by wyarde** [comment]
Thanks for providing the logs.

From what I can tell from the above, everything works as intended. But I do see why it is confusing.

```
ERRO[0001] fatal: couldn't find remote ref refs/notes/gino_keva
```

This error is actually "expected" since it's the direct output of the Git CLI. Gino keva is trying to fetch prior notes, however since this is the first time there's no upstream gino_keva ref that could be fetched. I will see how to catch this error and provide a reasonable output (probably only with verbose flag) to avoid this confusing

Also, I realize now that it's probably reasonable to have a digit at the end of a key name. I will adjust the code to allow for that as well, since there's no technical reason to not allow for it.

Would the 2 above improvements resolve the issues/confusion you were facing? Also, if you have other ideas/suggestions do let me know either here or in a separate issue.

**Comment by wafec** [comment]
It would be nice to have this. Indeed, it was kinda confusing at first. And yes, to have the option of adding numbers at the end of a key name definition is very desirable in some use cases.

Currently, we at CCO are developing a solution using the tool, and the two things I need are to set and get a key/values and the best thing the tool offers to me is that I can do that through Git thus no need for object store servers for instance. I was wondering if these FATAL errors were hampering from getting this functionality but as pointed out I can proceed with the implementation with no fear. Thanks for helping me understand what was going on.

**Comment by wyarde** [comment]
Keeping this issue open until the outstandig bug has been resolved

**Comment by wyarde** [comment]
@wafec A new release v1.1.0 has been created addressing the above issues. Would be great if you could try again and confirm it now works as expected
